### PR TITLE
Was missing React Import

### PR DESCRIPTION
**Pull request by shivamsinha15**

### CODE REVIEW

**Comment by shrugs** [comment]
In this snippet the `React` variable isn't required immediately, so I'd prefer to avoid including it. ESLint will most likely treat the unused variable as a warning/error.

**Comment by shivamsinha15** [comment]
Hey mate ... even though its not explicitly required the render function does use it implicitly. Otherwise is complains: 

> Can't find variable: React render YourComponent.js 

and since majority of components do use the render function. I think its best to import the variable `React` as well.

**Comment by shrugs** [comment]
Oh whoops! that's what I get for not thoroughly testing this. will squash and merge this

**Comment by shrugs** [comment]
Should be fixed in [this release](https://github.com/Shrugs/react-native-snippets/releases/tag/v1.1.1), and should be on package control in an hour, thanks for the heads up!

**Pull request closed without merging**
